### ISSUE TITLE
I get 0-byte zip files

### ISSUE THREAD

**Issue by Poikilos** [vladignatyev/crx-extractor#7] opened 2019-05-01 11:37 UTC
OS: Fedora 29
Browser: (any)
* Firefox 66.0.3 64-bit
* Brave Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)

Extension: <https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta>

**Comment by vladignatyev** [comment] 2019-05-02 17:16
@poikilos thanks for report! I have reproduced, will investigate

**Comment by Poikilos** [comment] 2019-05-02 21:16
If you don't yet support crx version 3, just skip the signature key length (AND signature key) unless the version is <= 2 as shown here: <https://github.com/poikilos/uncrx/blob/master/uncrx.py#L116>

**Comment by CedricMi** [comment] 2019-05-08 07:07
Hi also get a 0-byte zip file with the following crx file (from a French grammar/spellchecker)
[Adaptateur Google Chrome.crx](https://we.tl/t-ZUEBoIaHB5)

**Comment by vladignatyev** [comment] 2019-08-02 21:10
@CedricMi @poikilos  Probably resolved by the latest commit. Check out on the website: https://crxextractor.com/

If you check and it been resolved, please remind me or close this issue!

**Comment by CedricMi** [comment] 2019-08-05 09:50
Thanks Vladimir,
It does indeed work, at least with the file I was interested in.
The issue is resolved for me.

**Closed as completed** 2019-12-19 12:01 UTC
